### ISSUE TITLE
GitHub Actionsがたまにコケる

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/official#240]

**Comment by tyokinuhata** [comment]
例えばこれ: https://github.com/uyupun/official/actions/runs/5343390128/jobs/9686411714

**Comment by tyokinuhata** [comment]
エラーログ

```
Push the commit or tag
  /usr/bin/git push origin gh-pages
  To https://github.com/uyupun/official.git
   ! [remote rejected] gh-pages -> gh-pages (cannot lock ref 'refs/heads/gh-pages': is at e96ade2891f2911d873f6cd5[61](https://github.com/uyupun/official/actions/runs/5343390128/jobs/9686411714#step:11:67)48e469b912ecf6 but expected 9ace04a5e348b4b0825436a09377eb98b01e618e)
  error: failed to push some refs to 'https://github.com/uyupun/official.git'
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```

**Comment by tyokinuhata** [comment]
このエラーメッセージは、`gh-pages`ブランチへのプッシュが拒否されたことを示しています。具体的には、ローカルの`gh-pages`ブランチの最新のコミットと、リモートの`gh-pages`ブランチの最新のコミットが一致しないために発生しています。

一般的には、このエラーは他のプロセス（おそらく他のGitHub Actionsのジョブやワークフロー）が同じブランチを同時に更新しようとしたときに発生します。これにより、ローカルとリモートの`gh-pages`ブランチの間で競合が生じています。

この問題を解決するには、次のようなアプローチが考えられます：

1. リモートの変更をプルする：ローカルの`gh-pages`ブランチで`git pull origin gh-pages`を実行し、リモートの最新の変更を取り込みます。その後、必要に応じて手動で競合を解消し、再度プッシュします。

2. 並列実行を防ぐ：ジョブやワークフローが同じブランチを同時に更新しないようにスケジューリングを調整します。これにより、この問題を根本的に解消することができます。

3. 強制的にプッシュする：`git push --force origin gh-pages`を実行することで、ローカルの`gh-pages`ブランチを強制的にリモートにプッシュします。ただし、この方法は他の変更を上書きしてしまう可能性があり、注意が必要です。

**Comment by tyokinuhata** [comment]
つまり、

1. Lighthouseがリポジトリにチェックアウト
2. Storybookがリポジトリにプッシュ
3. Lighthouseがリポジトリにプッシュ <- ここで問題発生

という流れだと思われる

**Comment by tyokinuhata** [comment]
ワークフローを直列で実行することで回避できるが、大部分は並列で実行させたほうが効率が良いのでできればしたくない

**Comment by tyokinuhata** [comment]
GitHub Actionsには、ジョブレベルで自動リトライの機能があります。これにより、ジョブが失敗した場合に自動的に再試行することができます。この機能は特に、ネットワークの問題や一時的なサービスのダウンタイムなど、一時的な問題が原因でジョブが失敗する場合に有用です。

以下に、ジョブの自動リトライを設定する方法を示します。

```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        run: |
          # Your commands here...
    timeout-minutes: 10
    # Automatically retry this job up to 3 times if it fails.
    # The job must be idempotent.
    strategy:
      max-attempts: 3
```

この設定では、`max-attempts`を使用して、ジョブが失敗した場合に再試行する最大回数を指定します。この例では、ジョブが失敗した場合に最大3回まで自動的に再試行されます。

ただし、注意点としてジョブは冪等性(idempotent)を持つ必要があります。つまり、ジョブを複数回実行しても同じ結果が得られ、副作用がないことが必要です。再試行するジョブが副作用を持つ場合、予期しない結果や問題を引き起こす可能性があります。

また、この自動リトライ機能はジョブレベルでのみ利用可能であり、ステップレベルでは使用することができません。そのため、ステップ単位でのリトライを行いたい場合は、スクリプト内で適切なエラーハンドリングと再試行ロジックを実装する必要があります。
